# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-05 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sce_name', models.CharField(default='a', max_length=8, unique=True, verbose_name='景点名称')),
                ('sce_topic', models.CharField(default='a', max_length=15, verbose_name='主题名称')),
                ('brief_des', models.CharField(default='a', max_length=40, verbose_name='景点简述')),
                ('address', models.CharField(default='a', max_length=40, verbose_name='地址')),
                ('assessment', models.CharField(default='a', max_length=100, verbose_name='评价')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='价格')),
                ('cut_off_time', models.DateField(default='2019-09-20', verbose_name='优惠截止时间')),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='景点图片')),
            ],
        ),
    ]
