# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-05 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scen',
            name='address',
            field=models.CharField(default='', max_length=40, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='scen',
            name='assessment',
            field=models.CharField(default='', max_length=100, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='scen',
            name='brief_des',
            field=models.CharField(default='', max_length=40, verbose_name='景点简述'),
        ),
        migrations.AlterField(
            model_name='scen',
            name='sce_name',
            field=models.CharField(default='', max_length=8, unique=True, verbose_name='景点名称'),
        ),
        migrations.AlterField(
            model_name='scen',
            name='sce_topic',
            field=models.CharField(default='', max_length=15, verbose_name='主题名称'),
        ),
    ]
