# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='用户id')),
                ('g_img', models.ImageField(upload_to='static/images', verbose_name='商品图片')),
                ('g_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('time1', models.CharField(max_length=50, verbose_name='时间1')),
                ('time2', models.CharField(max_length=50, verbose_name='时间2')),
                ('g_type', models.CharField(max_length=50, verbose_name='商品类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('g_num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('serial_num', models.CharField(max_length=50, verbose_name='流水号')),
                ('is_pay', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='History_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(db_index=True, verbose_name='用户id')),
                ('g_img', models.ImageField(upload_to='static/images', verbose_name='商品图片')),
                ('g_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('time1', models.CharField(max_length=50, verbose_name='时间1')),
                ('time2', models.CharField(max_length=50, verbose_name='时间2')),
                ('g_type', models.CharField(max_length=50, verbose_name='商品类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('g_num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('booking_time', models.DateTimeField(auto_now_add=True, verbose_name='订单时间')),
                ('serial_num', models.CharField(max_length=50, verbose_name='流水号')),
                ('is_del', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, unique=True, verbose_name='用户姓名')),
                ('upwd', models.CharField(max_length=250, verbose_name='用户密码')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='余额')),
                ('is_online', models.BooleanField(default=0, verbose_name='登录状态')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('is_alive', models.BooleanField(default=0, verbose_name='是否注销')),
            ],
        ),
    ]
