# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-06 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='head_img',
            field=models.ImageField(null=True, upload_to='static/images', verbose_name='用户头像'),
        ),
    ]
