# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-09 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_info_head_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='head_img',
            field=models.ImageField(default='head.jpg', upload_to='static/images/user/change', verbose_name='用户头像'),
        ),
    ]
