# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-09 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190709_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='head_img',
            field=models.ImageField(default='head.jpg', upload_to='', verbose_name='用户头像'),
        ),
    ]
