# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-09 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190709_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='head_img',
            field=models.ImageField(upload_to='static/images/user/change', verbose_name='用户头像'),
        ),
    ]
