# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-28 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='is_alive',
            field=models.BooleanField(default=0, verbose_name='是否注销'),
        ),
        migrations.AddField(
            model_name='info',
            name='is_online',
            field=models.BooleanField(default=0, verbose_name='登录状态'),
        ),
        migrations.AddField(
            model_name='info',
            name='join_time',
            field=models.DateTimeField(auto_now=True, verbose_name='注册时间'),
        ),
        migrations.AddField(
            model_name='info',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='info',
            name='uname',
            field=models.CharField(max_length=50, unique=True, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='info',
            name='upwd',
            field=models.CharField(max_length=150, verbose_name='用户密码'),
        ),
    ]
