# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-28 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190628_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
