# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-29 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190628_1957'),
        ('user', '0010_auto_20190628_2026'),
    ]

    operations = [
    ]
