# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_merge_20190701_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='info',
            name='upwd',
            field=models.CharField(max_length=250, verbose_name='用户密码'),
        ),
    ]
