# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-03 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190702_2015'),
        ('user', '0014_merge_20190702_1829'),
    ]

    operations = [
    ]
