# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-02 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190702_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_list',
            name='is_del',
            field=models.BooleanField(default=True),
        ),
    ]
