# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-05 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_merge_20190705_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='serial_num',
            field=models.CharField(default=100, max_length=50, verbose_name='流水号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history_list',
            name='booking_time',
            field=models.DateTimeField(verbose_name='订单时间'),
        ),
    ]
