# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-03 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_merge_20190703_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='serial_num',
        ),
    ]
