# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-03 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_cart_serial_num'),
        ('user', '0014_merge_20190702_1846'),
    ]

    operations = [
    ]
