# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-05 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(max_length=30, null=True, verbose_name='经纬度')),
                ('scbr', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenic.Scbr')),
            ],
        ),
    ]
