# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-29 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduce',
            name='sce_name2',
        ),
        migrations.RemoveField(
            model_name='scbr',
            name='scp',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sce_name3',
        ),
        migrations.DeleteModel(
            name='Introduce',
        ),
        migrations.DeleteModel(
            name='Scbr',
        ),
        migrations.DeleteModel(
            name='Scen',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
