# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-06 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0002_scen2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scen2',
            name='sce_name',
            field=models.CharField(default='', max_length=8, verbose_name='景点名称'),
        ),
    ]
