# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-06 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0004_auto_20190706_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scen2',
            name='price',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=6, verbose_name='价格'),
        ),
    ]
