# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-09 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0005_auto_20190706_1554'),
        ('scenic', '0003_auto_20190706_0945'),
    ]

    operations = [
    ]
