# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=20, verbose_name='酒店名字')),
                ('address', models.CharField(max_length=100, verbose_name='酒店地址')),
                ('phone', models.CharField(max_length=50, verbose_name='酒店电话')),
                ('info', models.TextField(verbose_name='酒店详细信息')),
                ('hotel_level', models.CharField(max_length=10, verbose_name='酒店级别')),
                ('hotel_p', models.CharField(default='/', max_length=25, verbose_name='图片地址')),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=20, verbose_name='酒店名')),
                ('house_count', models.IntegerField(default=30, verbose_name='剩余房间数量')),
                ('order_count', models.IntegerField(default=0, verbose_name='下单次数')),
                ('hotel_p', models.CharField(default='/', max_length=25, verbose_name='图片地址')),
            ],
            options={
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20, verbose_name='房间名')),
                ('area', models.CharField(max_length=10, verbose_name='面积')),
                ('price', models.CharField(max_length=10, verbose_name='价位')),
                ('iprice', models.IntegerField(default=1, verbose_name='数字价位')),
                ('window', models.CharField(max_length=20, verbose_name='窗')),
                ('bed', models.CharField(max_length=100, verbose_name='床')),
                ('room_level', models.CharField(default='1', max_length=5, verbose_name='房间编号')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.House')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='house',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.House'),
        ),
    ]
