# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_p',
        ),
    ]
