# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-06 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_hotel_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='house',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
