# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-28 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_hotel_hotel_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_user_id', models.CharField(max_length=5, verbose_name='用户id')),
                ('test_hotel_id', models.CharField(max_length=5, verbose_name='酒店id')),
                ('test_room_name', models.CharField(max_length=20, verbose_name='房间名')),
                ('test_area', models.CharField(max_length=10, verbose_name='面积')),
                ('test_price', models.CharField(max_length=10, verbose_name='价位')),
                ('test_window', models.CharField(max_length=20, verbose_name='窗')),
                ('test_bed', models.CharField(max_length=100, verbose_name='床')),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
