# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-28 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_test_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_book',
        ),
    ]
