# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_delete_test_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_level',
            field=models.IntegerField(default=1, verbose_name='房间编号'),
        ),
    ]
