# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-28 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_room_room_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_level',
        ),
    ]
