# -*- coding: utf-8 -*-
<<<<<<< HEAD:Travel/hotel/migrations/0015_room_iprice.py
# Generated by Django 1.11.8 on 2019-07-02 18:48
=======
# Generated by Django 1.11.8 on 2019-07-03 13:06
>>>>>>> b06301074f86e97101feba6a7f37aa48fc48b231:Travel/hotel/migrations/0015_room_iprice.py
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_room_room_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='iprice',
            field=models.IntegerField(default=1, verbose_name='数字价位'),
        ),
    ]
