# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-02 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_auto_20190702_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
